# This compose file can be useful to develop and debug Jupyterhub code locally.
# It is not meant to be deployed in production.

version: '3'

services:
  jupyterhub:
    build: jupyterhub/dev
    container_name: jupyterhub
    depends_on:
      - postgres
    environment:
      JUPYTER_IMAGE: openhexa-base-notebook
      DOCKER_NETWORK_NAME: openhexa-notebooks_default
      HUB_IP: jupyterhub
      HUB_DB_URL: postgresql://postgres:postgres@postgres:5432/jupyterhub
      APP_URL: http://localhost:8000
      APP_CREDENTIALS_URL: http://host.docker.internal:8000/notebooks/credentials/
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jupyterhub/dev/:/srv/jupyterhub/
    ports:
      - 8001:8000
    restart: on-failure

  jupyter:  # just used for building - the jupyterhub service will spawn jupyter containers on demand
    build: jupyter
    image: openhexa-base-notebook
    command: echo

  postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jupyterhub