# This compose file can be useful to develop and debug Jupyterhub code locally.
# It is not meant to be deployed in production.

version: '3'

services:
  jupyterhub:
    build:
      context: jupyterhub
      dockerfile: Dockerfile.dev
    command: ["jupyterhub", "-f", "/etc/jupyterhub/jupyterhub_dev_config.py"]
    container_name: jupyterhub
    depends_on:
      - postgres
    environment:
      LOAD_DEV_CONFIG: "true"
      JUPYTER_IMAGE: openhexa-base-notebook
      DOCKER_NETWORK_NAME: openhexa-notebooks_default
      HUB_IP: jupyterhub
      HUB_DB_URL: postgresql://postgres:postgres@postgres:5432/jupyterhub
      APP_CREDENTIALS_URL: http://host.docker.internal:8000/notebooks/credentials/
      CONTENT_SECURITY_POLICY: "frame-ancestors 'self' localhost:*"
      JUPYTERHUB_CRYPT_KEY: 0b9c2791baa0b19e10f1dc9c4a1a702dda0a37c332378870e9542271a365b9b8
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jupyterhub/config/:/etc/jupyterhub/
    ports:
      - 8001:8000
    restart: on-failure

  jupyter:  # just used for building - the jupyterhub service will spawn jupyter containers on demand
    build: jupyter
    image: openhexa-base-notebook
    command: echo

  postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jupyterhub