# The version here MUST match the z2jh chart version
# URL: https://hub.jupyter.org/helm-chart/
FROM jupyterhub/k8s-hub:3.3.3

COPY config/jupyterhub_config.py /usr/local/etc/jupyterhub/jupyterhub_config.d/
