# This Dockerfile is only intended for development
# In z2jh mode, we use the image provided by the Zero to Jupyterhub Helm chart (first column of the following link)
# It is crucial to use the same jupyterhub version than the one used by z2jh
# URL: https://hub.jupyter.org/helm-chart/
FROM jupyterhub/jupyterhub:5.2.1

COPY config/jupyterhub_config_base.py /etc/jupyterhub/jupyterhub_config.d/jupyterhub_base_config.py
COPY config/jupyterhub_config_docker.py /etc/jupyterhub/jupyterhub_config.d/jupyterhub_config.py

RUN pip install --upgrade pip
RUN pip install dockerspawner==13.* psycopg2-binary==2.*
