# This Dockerfile is only intended for development
# In z2jh mode, we use the image provided by the Zero to Jupyterhub Helm chart (first column of the following link)
# It is crucial to use the same jupyterhub version than the one used by z2jh
# URL: https://hub.jupyter.org/helm-chart/
FROM jupyterhub/jupyterhub:4.1.1


COPY config/* /etc/jupyterhub/

RUN pip install --upgrade pip
RUN pip install dockerspawner==13.* psycopg2-binary==2.*
